export const MEDIA_PROVIDER_CONNECTION_PREFIX = 'media-provider:'

export const MEDIA_PROVIDER_KINDS = ['image', 'video', 'audio'] as const

export type MediaProviderKind = (typeof MEDIA_PROVIDER_KINDS)[number]
export type MediaProviderLocale = 'en' | 'zh' | 'ja' | 'ko'
export type MediaService =
  | 'image-generation'
  | 'image-edit'
  | 'video-generation'
  | 'speech-to-text'
  | 'text-to-speech'
  | 'music-generation'

export type MediaProviderModel = {
  id: string
  label: string
  service: MediaService
}

export type MediaCredentialField = {
  id: string
  label: string
  placeholder: string
  secret: boolean
  required: boolean
}

export type MediaProviderTestAuth =
  | {
      type: 'bearer'
      fieldId: string
    }
  | {
      type: 'header'
      fieldId: string
      headerName: string
      prefix?: string
    }
  | {
      type: 'basic'
      fieldId: string
    }
  | {
      type: 'none'
    }

export type MediaProviderDefinition = {
  kind: MediaProviderKind
  id: string
  runtimeProviderId: string
  credentialGroupId: string
  names: Record<MediaProviderLocale, string>
  logoProviderId: string
  website: string
  baseUrl: string
  connectionMode: 'api-key' | 'credentials' | 'none' | 'local'
  credentialFields: readonly MediaCredentialField[]
  sharedPresetIds: readonly string[]
  defaultModel: string
  models: readonly MediaProviderModel[]
  chinaPriority: boolean
  source: 'omniroute' | 'cybercode'
  test?: {
    url: string
    method?: 'GET' | 'HEAD'
    auth: MediaProviderTestAuth
  }
}

const apiKeyField = (
  label = 'API Key',
  placeholder = 'sk-...',
): readonly MediaCredentialField[] => [
  {
    id: 'apiKey',
    label,
    placeholder,
    secret: true,
    required: true,
  },
]

const noCredentials: readonly MediaCredentialField[] = []

const tencentCredentials: readonly MediaCredentialField[] = [
  {
    id: 'secretId',
    label: 'SecretId',
    placeholder: 'AKID...',
    secret: false,
    required: true,
  },
  {
    id: 'secretKey',
    label: 'SecretKey',
    placeholder: 'SecretKey',
    secret: true,
    required: true,
  },
]

const playHtCredentials: readonly MediaCredentialField[] = [
  {
    id: 'userId',
    label: 'User ID',
    placeholder: 'PlayHT User ID',
    secret: false,
    required: true,
  },
  {
    id: 'apiKey',
    label: 'API Key',
    placeholder: 'PlayHT API Key',
    secret: true,
    required: true,
  },
]

function names(
  en: string,
  zh: string,
  ja: string = en,
  ko: string = en,
): Record<MediaProviderLocale, string> {
  return { en, zh, ja, ko }
}

function models(
  service: MediaService,
  ...items: Array<[string, string]>
): readonly MediaProviderModel[] {
  return items.map(([id, label]) => ({ id, label, service }))
}

function mixedModels(
  ...items: Array<[string, string, MediaService]>
): readonly MediaProviderModel[] {
  return items.map(([id, label, service]) => ({ id, label, service }))
}

const IMAGE_PROVIDERS: readonly MediaProviderDefinition[] = [
  {
    kind: 'image',
    id: 'volcengine-seedream',
    runtimeProviderId: 'volcengine',
    credentialGroupId: 'volcengine',
    names: names('Volcengine Seedream', '火山引擎 Seedream', 'Volcengine Seedream', 'Volcengine Seedream'),
    logoProviderId: 'volcengine',
    website: 'https://www.volcengine.com/product/ark',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3/images/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Ark API Key'),
    sharedPresetIds: ['volcengine'],
    defaultModel: 'doubao-seedream-4-5-251128',
    models: models(
      'image-generation',
      ['doubao-seedream-4-5-251128', 'Seedream 4.5'],
      ['doubao-seedream-4-0-250828', 'Seedream 4.0'],
    ),
    chinaPriority: true,
    source: 'cybercode',
    test: {
      url: 'https://ark.cn-beijing.volces.com/api/v3/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'image',
    id: 'alibaba-wan-image',
    runtimeProviderId: 'alibaba',
    credentialGroupId: 'alibaba',
    names: names('Alibaba Wan Image', '阿里云通义万相', 'Alibaba Wan Image', 'Alibaba Wan Image'),
    logoProviderId: 'alibaba',
    website: 'https://www.alibabacloud.com/help/en/model-studio/image-generation',
    baseUrl: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('DashScope API Key'),
    sharedPresetIds: ['alibaba'],
    defaultModel: 'wan2.6-t2i',
    models: models(
      'image-generation',
      ['wan2.6-t2i', 'Wan 2.6 Image'],
      ['wanx2.1-t2i-turbo', 'Wanx 2.1 Turbo'],
      ['wanx2.1-t2i-plus', 'Wanx 2.1 Plus'],
    ),
    chinaPriority: true,
    source: 'cybercode',
    test: {
      url: 'https://dashscope.aliyuncs.com/api/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'image',
    id: 'sensenova',
    runtimeProviderId: 'sensenova',
    credentialGroupId: 'sensenova',
    names: names('SenseNova Image', '商汤日日新生图', 'SenseNova Image', 'SenseNova Image'),
    logoProviderId: 'sensenova',
    website: 'https://platform.sensenova.cn',
    baseUrl: 'https://api.sensenova.cn/v1/images/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'sensenova-u1-fast',
    models: models('image-generation', ['sensenova-u1-fast', 'SenseNova U1 Fast']),
    chinaPriority: true,
    source: 'omniroute',
    test: {
      url: 'https://api.sensenova.cn/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'image',
    id: 'kie',
    runtimeProviderId: 'kie',
    credentialGroupId: 'kie',
    names: names(
      'KIE (Seedream / Qwen / Wan)',
      'KIE（Seedream / 千问 / 万相）',
      'KIE (Seedream / Qwen / Wan)',
      'KIE (Seedream / Qwen / Wan)',
    ),
    logoProviderId: 'kie',
    website: 'https://kie.ai',
    baseUrl: 'https://api.kie.ai',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('KIE API Key'),
    sharedPresetIds: [],
    defaultModel: 'seedream/5.0-lite-text-to-image',
    models: models(
      'image-generation',
      ['seedream/5.0-lite-text-to-image', 'Seedream 5.0 Lite'],
      ['seedream/4.5-text-to-image', 'Seedream 4.5'],
      ['qwen2/text-to-image', 'Qwen2 Image'],
      ['wan/2.7-image-pro', 'Wan 2.7 Image Pro'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.kie.ai/api/v1/chat/credit',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'image',
    id: 'fal-ai',
    runtimeProviderId: 'fal-ai',
    credentialGroupId: 'fal-ai',
    names: names('Fal AI (Seedream / Dreamina)', 'Fal AI（Seedream / 即梦）'),
    logoProviderId: 'fal-ai',
    website: 'https://fal.ai/models',
    baseUrl: 'https://fal.run',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('FAL_KEY', 'fal_...'),
    sharedPresetIds: [],
    defaultModel: 'fal-ai/bytedance/seedream/v4.5/text-to-image',
    models: models(
      'image-generation',
      ['fal-ai/bytedance/seedream/v4.5/text-to-image', 'Seedream 4.5'],
      ['fal-ai/bytedance/dreamina/v3.1/text-to-image', 'Dreamina 3.1'],
      ['fal-ai/flux-2-max', 'FLUX.2 Max'],
      ['fal-ai/nano-banana-2', 'Nano Banana 2'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://fal.run',
      auth: { type: 'header', fieldId: 'apiKey', headerName: 'Authorization', prefix: 'Key ' },
    },
  },
  {
    kind: 'image',
    id: 'together',
    runtimeProviderId: 'together',
    credentialGroupId: 'together',
    names: names('Together AI Image', 'Together AI 图像'),
    logoProviderId: 'together',
    website: 'https://www.together.ai',
    baseUrl: 'https://api.together.xyz/v1/images/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'Qwen/Qwen-Image-2.0',
    models: models(
      'image-generation',
      ['Qwen/Qwen-Image-2.0', 'Qwen Image 2.0'],
      ['black-forest-labs/FLUX.2-max', 'FLUX.2 Max'],
      ['black-forest-labs/FLUX.2-pro', 'FLUX.2 Pro'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.together.xyz/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'image',
    id: 'openai',
    runtimeProviderId: 'openai',
    credentialGroupId: 'openai',
    names: names('OpenAI Image', 'OpenAI 图像'),
    logoProviderId: 'openai',
    website: 'https://platform.openai.com',
    baseUrl: 'https://api.openai.com/v1/images/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['openai'],
    defaultModel: 'gpt-image-2',
    models: models(
      'image-generation',
      ['gpt-image-2', 'GPT Image 2'],
      ['gpt-image-1.5', 'GPT Image 1.5'],
      ['gpt-image-1-mini', 'GPT Image 1 Mini'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.openai.com/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'image',
    id: 'xai',
    runtimeProviderId: 'xai',
    credentialGroupId: 'xai',
    names: names('xAI Grok Imagine', 'xAI Grok Imagine'),
    logoProviderId: 'xai',
    website: 'https://console.x.ai',
    baseUrl: 'https://api.x.ai/v1/images/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['xai'],
    defaultModel: 'grok-imagine-image-quality',
    models: models(
      'image-generation',
      ['grok-imagine-image-quality', 'Grok Imagine Image Quality'],
      ['grok-imagine-image', 'Grok Imagine Image'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.x.ai/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'image',
    id: 'openrouter',
    runtimeProviderId: 'openrouter',
    credentialGroupId: 'openrouter',
    names: names('OpenRouter Image', 'OpenRouter 图像'),
    logoProviderId: 'openrouter',
    website: 'https://openrouter.ai',
    baseUrl: 'https://openrouter.ai/api/v1/images/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['openrouter'],
    defaultModel: 'openai/gpt-5.4-image-2',
    models: models(
      'image-generation',
      ['openai/gpt-5.4-image-2', 'GPT Image 2'],
      ['google/gemini-3.1-flash-image-preview', 'Nano Banana 2'],
      ['black-forest-labs/flux.2-max', 'FLUX.2 Max'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://openrouter.ai/api/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'image',
    id: 'vertex',
    runtimeProviderId: 'vertex',
    credentialGroupId: 'vertex',
    names: names('Google Vertex Image', 'Google Vertex 图像'),
    logoProviderId: 'google',
    website: 'https://cloud.google.com/vertex-ai/generative-ai',
    baseUrl: 'https://us-central1-aiplatform.googleapis.com/v1',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Google access token'),
    sharedPresetIds: ['google'],
    defaultModel: 'imagen-4.0-generate-001',
    models: models(
      'image-generation',
      ['imagen-4.0-generate-001', 'Imagen 4'],
      ['imagen-4.0-fast-generate-001', 'Imagen 4 Fast'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'stability-ai',
    runtimeProviderId: 'stability-ai',
    credentialGroupId: 'stability-ai',
    names: names('Stability AI', 'Stability AI'),
    logoProviderId: 'stability-ai',
    website: 'https://platform.stability.ai',
    baseUrl: 'https://api.stability.ai',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'stable-image-ultra',
    models: mixedModels(
      ['stable-image-ultra', 'Stable Image Ultra', 'image-generation'],
      ['stable-image-core', 'Stable Image Core', 'image-generation'],
      ['inpaint', 'Inpaint', 'image-edit'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'black-forest-labs',
    runtimeProviderId: 'black-forest-labs',
    credentialGroupId: 'black-forest-labs',
    names: names('Black Forest Labs', 'Black Forest Labs'),
    logoProviderId: 'black-forest-labs',
    website: 'https://bfl.ai',
    baseUrl: 'https://api.bfl.ai',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('BFL API Key'),
    sharedPresetIds: [],
    defaultModel: 'flux-2-max',
    models: mixedModels(
      ['flux-2-max', 'FLUX.2 Max', 'image-generation'],
      ['flux-2-pro', 'FLUX.2 Pro', 'image-generation'],
      ['flux-kontext-max', 'FLUX Kontext Max', 'image-edit'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'recraft',
    runtimeProviderId: 'recraft',
    credentialGroupId: 'recraft',
    names: names('Recraft', 'Recraft'),
    logoProviderId: 'recraft',
    website: 'https://www.recraft.ai',
    baseUrl: 'https://external.api.recraft.ai',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'recraftv4_pro',
    models: models(
      'image-generation',
      ['recraftv4_pro', 'Recraft V4 Pro'],
      ['recraftv4', 'Recraft V4'],
      ['recraftv3', 'Recraft V3'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'ideogram',
    runtimeProviderId: 'ideogram',
    credentialGroupId: 'ideogram',
    names: names('Ideogram', 'Ideogram'),
    logoProviderId: 'ideogram',
    website: 'https://ideogram.ai',
    baseUrl: 'https://api.ideogram.ai/generate',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'V_3',
    models: models(
      'image-generation',
      ['V_3', 'Ideogram V3'],
      ['V_2A', 'Ideogram V2A'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'fireworks',
    runtimeProviderId: 'fireworks',
    credentialGroupId: 'fireworks',
    names: names('Fireworks AI Image', 'Fireworks AI 图像'),
    logoProviderId: 'fireworks',
    website: 'https://fireworks.ai',
    baseUrl: 'https://api.fireworks.ai/inference/v1/image_generation/accounts/fireworks/models',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['fireworks'],
    defaultModel: 'flux-1-schnell-fp8',
    models: models(
      'image-generation',
      ['flux-1-schnell-fp8', 'FLUX.1 Schnell'],
      ['playground-v2-5-1024px-aesthetic', 'Playground v2.5'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'nvidia',
    runtimeProviderId: 'nvidia',
    credentialGroupId: 'nvidia',
    names: names('NVIDIA NIM Image', 'NVIDIA NIM 图像'),
    logoProviderId: 'nvidia',
    website: 'https://build.nvidia.com',
    baseUrl: 'https://ai.api.nvidia.com/v1/genai',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['nvidia'],
    defaultModel: 'black-forest-labs/flux.2-klein-4b',
    models: mixedModels(
      ['black-forest-labs/flux.2-klein-4b', 'FLUX.2 Klein 4B', 'image-generation'],
      ['black-forest-labs/flux.1-dev', 'FLUX.1 Dev', 'image-generation'],
      ['black-forest-labs/flux.1-kontext-dev', 'FLUX.1 Kontext Dev', 'image-edit'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'huggingface',
    runtimeProviderId: 'huggingface',
    credentialGroupId: 'huggingface',
    names: names('Hugging Face Image', 'Hugging Face 图像'),
    logoProviderId: 'huggingface',
    website: 'https://huggingface.co/models?pipeline_tag=text-to-image',
    baseUrl: 'https://api-inference.huggingface.co/models',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Hugging Face token', 'hf_...'),
    sharedPresetIds: ['huggingface'],
    defaultModel: 'black-forest-labs/FLUX.1-dev',
    models: models(
      'image-generation',
      ['black-forest-labs/FLUX.1-dev', 'FLUX.1 Dev'],
      ['black-forest-labs/FLUX.1-schnell', 'FLUX.1 Schnell'],
      ['stabilityai/stable-diffusion-xl-base-1.0', 'Stable Diffusion XL'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'leonardo',
    runtimeProviderId: 'leonardo',
    credentialGroupId: 'leonardo',
    names: names('Leonardo AI', 'Leonardo AI'),
    logoProviderId: 'leonardo',
    website: 'https://leonardo.ai',
    baseUrl: 'https://cloud.leonardo.ai/api/rest/v1/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'phoenix',
    models: models(
      'image-generation',
      ['phoenix', 'Phoenix'],
      ['sdxl', 'SDXL'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'haiper',
    runtimeProviderId: 'haiper',
    credentialGroupId: 'haiper',
    names: names('Haiper', 'Haiper'),
    logoProviderId: 'haiper',
    website: 'https://haiper.ai',
    baseUrl: 'https://api.haiper.ai/v1/jobs/gen2/text2image',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('HAIPER_KEY'),
    sharedPresetIds: [],
    defaultModel: 'gen2',
    models: models('image-generation', ['gen2', 'Gen 2 Image']),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'pollinations',
    runtimeProviderId: 'pollinations',
    credentialGroupId: 'pollinations',
    names: names('Pollinations Image', 'Pollinations 图像'),
    logoProviderId: 'pollinations',
    website: 'https://pollinations.ai',
    baseUrl: 'https://gen.pollinations.ai/v1/images/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'qwen-image',
    models: models(
      'image-generation',
      ['qwen-image', 'Qwen Image Plus'],
      ['wan-image', 'Wan 2.7 Image'],
      ['flux', 'FLUX Schnell'],
      ['gpt-image-2', 'GPT Image 2'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'nanobanana',
    runtimeProviderId: 'nanobanana',
    credentialGroupId: 'nanobanana',
    names: names('NanoBanana API', 'NanoBanana API'),
    logoProviderId: 'nanobanana',
    website: 'https://nanobananaapi.ai',
    baseUrl: 'https://api.nanobananaapi.ai/api/v1/nanobanana/generate',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'nanobanana-pro',
    models: models(
      'image-generation',
      ['nanobanana-pro', 'NanoBanana Pro'],
      ['nanobanana-flash', 'NanoBanana Flash'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'nanogpt',
    runtimeProviderId: 'nanogpt',
    credentialGroupId: 'nanogpt',
    names: names('NanoGPT Image', 'NanoGPT 图像'),
    logoProviderId: 'nanogpt',
    website: 'https://nano-gpt.com',
    baseUrl: 'https://nano-gpt.com/api/v1/images/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'qwen-image',
    models: models(
      'image-generation',
      ['qwen-image', 'Qwen Image'],
      ['z-image-turbo', 'Z-Image Turbo'],
      ['hidream', 'Hidream I1 Full'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'nebius',
    runtimeProviderId: 'nebius',
    credentialGroupId: 'nebius',
    names: names('Nebius AI Image', 'Nebius AI 图像'),
    logoProviderId: 'nebius',
    website: 'https://studio.nebius.ai',
    baseUrl: 'https://api.studio.nebius.ai/v1/images/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['nebius'],
    defaultModel: 'black-forest-labs/flux-dev',
    models: models(
      'image-generation',
      ['black-forest-labs/flux-dev', 'FLUX Dev'],
      ['black-forest-labs/flux-schnell', 'FLUX Schnell'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'topaz',
    runtimeProviderId: 'topaz',
    credentialGroupId: 'topaz',
    names: names('Topaz Labs', 'Topaz Labs'),
    logoProviderId: 'topaz',
    website: 'https://www.topazlabs.com',
    baseUrl: 'https://api.topazlabs.com',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'topaz-enhance',
    models: models('image-edit', ['topaz-enhance', 'Topaz Enhance']),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'image',
    id: 'comfyui',
    runtimeProviderId: 'comfyui',
    credentialGroupId: 'comfyui',
    names: names('ComfyUI', 'ComfyUI 本地'),
    logoProviderId: 'comfyui',
    website: 'https://www.comfy.org',
    baseUrl: 'http://127.0.0.1:8188',
    connectionMode: 'local',
    credentialFields: noCredentials,
    sharedPresetIds: [],
    defaultModel: 'flux-dev',
    models: models(
      'image-generation',
      ['flux-dev', 'FLUX Dev'],
      ['sdxl', 'SDXL'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'http://127.0.0.1:8188/system_stats',
      auth: { type: 'none' },
    },
  },
  {
    kind: 'image',
    id: 'sdwebui',
    runtimeProviderId: 'sdwebui',
    credentialGroupId: 'sdwebui',
    names: names('Stable Diffusion WebUI', 'Stable Diffusion WebUI 本地'),
    logoProviderId: 'stability-ai',
    website: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    baseUrl: 'http://127.0.0.1:7860',
    connectionMode: 'local',
    credentialFields: noCredentials,
    sharedPresetIds: [],
    defaultModel: 'sdxl-base-1.0',
    models: models(
      'image-generation',
      ['sdxl-base-1.0', 'SDXL Base 1.0'],
      ['stable-diffusion-v1-5', 'Stable Diffusion 1.5'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'http://127.0.0.1:7860/sdapi/v1/options',
      auth: { type: 'none' },
    },
  },
] as const

const VIDEO_PROVIDERS: readonly MediaProviderDefinition[] = [
  {
    kind: 'video',
    id: 'kie',
    runtimeProviderId: 'kie',
    credentialGroupId: 'kie',
    names: names(
      'KIE (Seedance 2.0 / Kling / Wan)',
      'KIE（Seedance 2.0 / 可灵 / 万相）',
      'KIE (Seedance 2.0 / Kling / Wan)',
      'KIE (Seedance 2.0 / Kling / Wan)',
    ),
    logoProviderId: 'kie',
    website: 'https://kie.ai',
    baseUrl: 'https://api.kie.ai',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('KIE API Key'),
    sharedPresetIds: [],
    defaultModel: 'bytedance/seedance-2',
    models: models(
      'video-generation',
      ['bytedance/seedance-2', 'Seedance 2.0'],
      ['kling-3.0/video', 'Kling 3.0'],
      ['wan/2-7-text-to-video', 'Wan 2.7 T2V'],
      ['hailuo/02-text-to-video-pro', 'Hailuo Pro T2V'],
    ),
    chinaPriority: true,
    source: 'omniroute',
    test: {
      url: 'https://api.kie.ai/api/v1/chat/credit',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'video',
    id: 'volcengine-seedance',
    runtimeProviderId: 'volcengine',
    credentialGroupId: 'volcengine',
    names: names('Volcengine Seedance', '火山引擎 Seedance'),
    logoProviderId: 'volcengine',
    website: 'https://www.volcengine.com/product/ark',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3/contents/generations/tasks',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Ark API Key'),
    sharedPresetIds: ['volcengine'],
    defaultModel: 'doubao-seedance-1-5-pro-251215',
    models: models(
      'video-generation',
      ['doubao-seedance-1-5-pro-251215', 'Seedance 1.5 Pro'],
    ),
    chinaPriority: true,
    source: 'cybercode',
    test: {
      url: 'https://ark.cn-beijing.volces.com/api/v3/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'video',
    id: 'minimax',
    runtimeProviderId: 'minimax',
    credentialGroupId: 'minimax',
    names: names('MiniMax Hailuo', 'MiniMax 海螺'),
    logoProviderId: 'minimax',
    website: 'https://platform.minimaxi.com/docs/guides/video-generation',
    baseUrl: 'https://api.minimaxi.com/v1/video_generation',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('MiniMax API Key'),
    sharedPresetIds: ['minimax'],
    defaultModel: 'MiniMax-Hailuo-2.3',
    models: models(
      'video-generation',
      ['MiniMax-Hailuo-2.3', 'Hailuo 2.3'],
      ['MiniMax-Hailuo-2.3-Fast', 'Hailuo 2.3 Fast'],
      ['MiniMax-Hailuo-02', 'Hailuo 02'],
      ['T2V-01-Director', 'T2V 01 Director'],
    ),
    chinaPriority: true,
    source: 'omniroute',
    test: {
      url: 'https://api.minimaxi.com/v1/files/list',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'video',
    id: 'alibaba',
    runtimeProviderId: 'alibaba',
    credentialGroupId: 'alibaba',
    names: names('Alibaba Wan Video', '阿里云万相视频'),
    logoProviderId: 'alibaba',
    website: 'https://www.alibabacloud.com/help/en/model-studio/image-to-video-general-api-reference',
    baseUrl: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('DashScope API Key'),
    sharedPresetIds: ['alibaba'],
    defaultModel: 'wan2.7-t2v',
    models: models(
      'video-generation',
      ['wan2.7-t2v', 'Wan 2.7 T2V'],
      ['wan2.7-i2v', 'Wan 2.7 I2V'],
    ),
    chinaPriority: true,
    source: 'omniroute',
    test: {
      url: 'https://dashscope.aliyuncs.com/api/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'video',
    id: 'tencent-mps',
    runtimeProviderId: 'tencent-mps',
    credentialGroupId: 'tencent-mps',
    names: names('Tencent Cloud AI Video', '腾讯云 AI 视频'),
    logoProviderId: 'tencent',
    website: 'https://cloud.tencent.com/document/product/862/132096',
    baseUrl: 'https://mps.tencentcloudapi.com',
    connectionMode: 'credentials',
    credentialFields: tencentCredentials,
    sharedPresetIds: [],
    defaultModel: 'hunyuan',
    models: models(
      'video-generation',
      ['hunyuan', 'Tencent Hunyuan Video'],
      ['kling', 'Kling Video'],
      ['hailuo', 'Hailuo Video'],
      ['vidu', 'Vidu Video'],
    ),
    chinaPriority: true,
    source: 'cybercode',
  },
  {
    kind: 'video',
    id: 'vertex',
    runtimeProviderId: 'vertex',
    credentialGroupId: 'vertex',
    names: names('Google Vertex Veo', 'Google Vertex Veo'),
    logoProviderId: 'google',
    website: 'https://cloud.google.com/vertex-ai/generative-ai/docs/video/overview',
    baseUrl: 'https://us-central1-aiplatform.googleapis.com/v1',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Google access token'),
    sharedPresetIds: ['google'],
    defaultModel: 'veo-3.0-generate-001',
    models: models(
      'video-generation',
      ['veo-3.0-generate-001', 'Veo 3.0'],
      ['veo-3.0-fast-generate-001', 'Veo 3.0 Fast'],
      ['veo-2.0-generate-001', 'Veo 2.0'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'video',
    id: 'runwayml',
    runtimeProviderId: 'runwayml',
    credentialGroupId: 'runwayml',
    names: names('Runway', 'Runway'),
    logoProviderId: 'runwayml',
    website: 'https://runwayml.com',
    baseUrl: 'https://api.dev.runwayml.com/v1',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Runway API Key'),
    sharedPresetIds: [],
    defaultModel: 'gen4.5',
    models: models(
      'video-generation',
      ['gen4.5', 'Gen-4.5'],
      ['gen4_turbo', 'Gen-4 Turbo'],
      ['gen3a_turbo', 'Gen-3 Alpha Turbo'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'video',
    id: 'replicate',
    runtimeProviderId: 'replicate',
    credentialGroupId: 'replicate',
    names: names('Replicate Video', 'Replicate 视频'),
    logoProviderId: 'replicate',
    website: 'https://replicate.com/collections/text-to-video',
    baseUrl: 'https://api.replicate.com/v1/predictions',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Replicate API token', 'r8_...'),
    sharedPresetIds: [],
    defaultModel: 'tencent/hunyuan-video',
    models: models(
      'video-generation',
      ['tencent/hunyuan-video', 'Tencent Hunyuan Video'],
      ['minimax/video-01', 'MiniMax Video 01'],
      ['wan-ai/wan2.1-t2v-480p', 'Wan 2.1 T2V'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'video',
    id: 'together',
    runtimeProviderId: 'together',
    credentialGroupId: 'together',
    names: names('Together AI Video', 'Together AI 视频'),
    logoProviderId: 'together',
    website: 'https://www.together.ai',
    baseUrl: 'https://api.together.xyz/videos',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'wan-ai/wan2.7-t2v',
    models: models(
      'video-generation',
      ['wan-ai/wan2.7-t2v', 'Wan 2.7 T2V'],
      ['wan-ai/wan2.1-t2v-480p', 'Wan 2.1 T2V'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.together.xyz/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'video',
    id: 'haiper',
    runtimeProviderId: 'haiper',
    credentialGroupId: 'haiper',
    names: names('Haiper Video', 'Haiper 视频'),
    logoProviderId: 'haiper',
    website: 'https://haiper.ai',
    baseUrl: 'https://api.haiper.ai/v1/jobs/gen2/text2video',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('HAIPER_KEY'),
    sharedPresetIds: [],
    defaultModel: 'gen2',
    models: models('video-generation', ['gen2', 'Gen 2']),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'video',
    id: 'leonardo',
    runtimeProviderId: 'leonardo',
    credentialGroupId: 'leonardo',
    names: names('Leonardo Video', 'Leonardo 视频'),
    logoProviderId: 'leonardo',
    website: 'https://leonardo.ai',
    baseUrl: 'https://cloud.leonardo.ai/api/rest/v1/generations',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'phoenix',
    models: models('video-generation', ['phoenix', 'Phoenix Video']),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'video',
    id: 'pollinations',
    runtimeProviderId: 'pollinations',
    credentialGroupId: 'pollinations',
    names: names('Pollinations Video', 'Pollinations 视频'),
    logoProviderId: 'pollinations',
    website: 'https://pollinations.ai',
    baseUrl: 'https://gen.pollinations.ai/video',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'default',
    models: models('video-generation', ['default', 'Pollinations Video']),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'video',
    id: 'comfyui',
    runtimeProviderId: 'comfyui',
    credentialGroupId: 'comfyui',
    names: names('ComfyUI Video', 'ComfyUI 本地视频'),
    logoProviderId: 'comfyui',
    website: 'https://www.comfy.org',
    baseUrl: 'http://127.0.0.1:8188',
    connectionMode: 'local',
    credentialFields: noCredentials,
    sharedPresetIds: [],
    defaultModel: 'animatediff',
    models: models(
      'video-generation',
      ['animatediff', 'AnimateDiff'],
      ['svd-xt', 'Stable Video Diffusion XT'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'http://127.0.0.1:8188/system_stats',
      auth: { type: 'none' },
    },
  },
  {
    kind: 'video',
    id: 'sdwebui',
    runtimeProviderId: 'sdwebui',
    credentialGroupId: 'sdwebui',
    names: names('Stable Diffusion WebUI Video', 'Stable Diffusion WebUI 本地视频'),
    logoProviderId: 'stability-ai',
    website: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    baseUrl: 'http://127.0.0.1:7860',
    connectionMode: 'local',
    credentialFields: noCredentials,
    sharedPresetIds: [],
    defaultModel: 'animatediff-webui',
    models: models('video-generation', ['animatediff-webui', 'AnimateDiff WebUI']),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'http://127.0.0.1:7860/sdapi/v1/options',
      auth: { type: 'none' },
    },
  },
  {
    kind: 'video',
    id: 'veoaifree-web',
    runtimeProviderId: 'veoaifree-web',
    credentialGroupId: 'veoaifree-web',
    names: names('Veo AI Free Web', 'Veo AI Free 网页入口'),
    logoProviderId: 'veoaifree-web',
    website: 'https://veoaifree.com',
    baseUrl: 'https://veoaifree.com/wp-admin/admin-ajax.php',
    connectionMode: 'none',
    credentialFields: noCredentials,
    sharedPresetIds: [],
    defaultModel: 'seedance',
    models: models(
      'video-generation',
      ['seedance', 'Seedance'],
      ['veo', 'Veo 3.1'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://veoaifree.com',
      auth: { type: 'none' },
    },
  },
] as const

const AUDIO_PROVIDERS: readonly MediaProviderDefinition[] = [
  {
    kind: 'audio',
    id: 'minimax',
    runtimeProviderId: 'minimax',
    credentialGroupId: 'minimax',
    names: names('MiniMax Audio & Music', 'MiniMax 语音与音乐'),
    logoProviderId: 'minimax',
    website: 'https://platform.minimaxi.com/docs',
    baseUrl: 'https://api.minimaxi.com/v1',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('MiniMax API Key'),
    sharedPresetIds: ['minimax'],
    defaultModel: 'speech-2.8-hd',
    models: mixedModels(
      ['speech-2.8-hd', 'Speech 2.8 HD', 'text-to-speech'],
      ['music-2.6', 'Music 2.6', 'music-generation'],
      ['music-2.6-free', 'Music 2.6 Free', 'music-generation'],
      ['music-cover', 'Music Cover', 'music-generation'],
    ),
    chinaPriority: true,
    source: 'omniroute',
    test: {
      url: 'https://api.minimaxi.com/v1/files/list',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'audio',
    id: 'xiaomi-mimo',
    runtimeProviderId: 'xiaomi-mimo',
    credentialGroupId: 'xiaomi-mimo',
    names: names('Xiaomi MiMo TTS', '小米 MiMo 语音'),
    logoProviderId: 'xiaomimimo',
    website: 'https://platform.xiaomimimo.com',
    baseUrl: 'https://api.xiaomimimo.com/v1/chat/completions',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('MiMo API Key'),
    sharedPresetIds: ['xiaomimimo'],
    defaultModel: 'mimo-v2.5-tts',
    models: models(
      'text-to-speech',
      ['mimo-v2.5-tts', 'MiMo V2.5 TTS'],
      ['mimo-v2.5-tts-voicedesign', 'MiMo Voice Design'],
      ['mimo-v2.5-tts-voiceclone', 'MiMo Voice Clone'],
    ),
    chinaPriority: true,
    source: 'omniroute',
    test: {
      url: 'https://api.xiaomimimo.com/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'audio',
    id: 'qwen-local',
    runtimeProviderId: 'qwen',
    credentialGroupId: 'qwen-local',
    names: names('Qwen Audio (Local)', '通义千问语音（本地）'),
    logoProviderId: 'qwen',
    website: 'https://github.com/QwenLM',
    baseUrl: 'http://127.0.0.1:8000/v1/audio',
    connectionMode: 'local',
    credentialFields: noCredentials,
    sharedPresetIds: [],
    defaultModel: 'qwen3-asr',
    models: mixedModels(
      ['qwen3-asr', 'Qwen3 ASR', 'speech-to-text'],
      ['qwen3-tts', 'Qwen3 TTS', 'text-to-speech'],
    ),
    chinaPriority: true,
    source: 'omniroute',
    test: {
      url: 'http://127.0.0.1:8000/v1/models',
      auth: { type: 'none' },
    },
  },
  {
    kind: 'audio',
    id: 'kie',
    runtimeProviderId: 'kie',
    credentialGroupId: 'kie',
    names: names('KIE Audio', 'KIE 音频'),
    logoProviderId: 'kie',
    website: 'https://kie.ai',
    baseUrl: 'https://api.kie.ai',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('KIE API Key'),
    sharedPresetIds: [],
    defaultModel: 'elevenlabs/text-to-speech-multilingual-v2',
    models: mixedModels(
      ['elevenlabs/text-to-speech-multilingual-v2', 'ElevenLabs TTS v2', 'text-to-speech'],
      ['elevenlabs/text-to-dialogue-v3', 'ElevenLabs Dialogue v3', 'text-to-speech'],
      ['elevenlabs/speech-to-text', 'ElevenLabs STT', 'speech-to-text'],
      ['elevenlabs/audio-isolation', 'Audio Isolation', 'speech-to-text'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.kie.ai/api/v1/chat/credit',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'audio',
    id: 'openai',
    runtimeProviderId: 'openai',
    credentialGroupId: 'openai',
    names: names('OpenAI Audio', 'OpenAI 音频'),
    logoProviderId: 'openai',
    website: 'https://platform.openai.com/docs/guides/audio',
    baseUrl: 'https://api.openai.com/v1/audio',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['openai'],
    defaultModel: 'gpt-4o-mini-tts',
    models: mixedModels(
      ['gpt-4o-mini-tts', 'GPT-4o Mini TTS', 'text-to-speech'],
      ['tts-1-hd', 'TTS 1 HD', 'text-to-speech'],
      ['gpt-4o-transcription', 'GPT-4o Transcription', 'speech-to-text'],
      ['whisper-1', 'Whisper 1', 'speech-to-text'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.openai.com/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'audio',
    id: 'vertex',
    runtimeProviderId: 'vertex',
    credentialGroupId: 'vertex',
    names: names('Google Vertex Audio', 'Google Vertex 音频'),
    logoProviderId: 'google',
    website: 'https://cloud.google.com/vertex-ai/generative-ai',
    baseUrl: 'https://us-central1-aiplatform.googleapis.com/v1',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Google access token'),
    sharedPresetIds: ['google'],
    defaultModel: 'gemini-3.1-flash-tts-preview',
    models: mixedModels(
      ['gemini-3.1-flash-tts-preview', 'Gemini 3.1 Flash TTS', 'text-to-speech'],
      ['gemini-2.5-pro-preview-tts', 'Gemini 2.5 Pro TTS', 'text-to-speech'],
      ['gemini-2.5-flash', 'Gemini 2.5 Flash Transcribe', 'speech-to-text'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'audio',
    id: 'groq',
    runtimeProviderId: 'groq',
    credentialGroupId: 'groq',
    names: names('Groq Speech', 'Groq 语音识别'),
    logoProviderId: 'groq',
    website: 'https://console.groq.com/docs/speech-text',
    baseUrl: 'https://api.groq.com/openai/v1/audio/transcriptions',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['groq'],
    defaultModel: 'whisper-large-v3-turbo',
    models: models(
      'speech-to-text',
      ['whisper-large-v3-turbo', 'Whisper Large v3 Turbo'],
      ['whisper-large-v3', 'Whisper Large v3'],
      ['distil-whisper-large-v3-en', 'Distil Whisper Large v3 EN'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.groq.com/openai/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'audio',
    id: 'deepgram',
    runtimeProviderId: 'deepgram',
    credentialGroupId: 'deepgram',
    names: names('Deepgram', 'Deepgram'),
    logoProviderId: 'deepgram',
    website: 'https://deepgram.com',
    baseUrl: 'https://api.deepgram.com/v1',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Deepgram API Key'),
    sharedPresetIds: [],
    defaultModel: 'nova-3',
    models: mixedModels(
      ['nova-3', 'Nova 3 STT', 'speech-to-text'],
      ['nova-2', 'Nova 2 STT', 'speech-to-text'],
      ['aura-asteria-en', 'Aura Asteria TTS', 'text-to-speech'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.deepgram.com/v1/projects',
      auth: { type: 'header', fieldId: 'apiKey', headerName: 'Authorization', prefix: 'Token ' },
    },
  },
  {
    kind: 'audio',
    id: 'elevenlabs',
    runtimeProviderId: 'elevenlabs',
    credentialGroupId: 'elevenlabs',
    names: names('ElevenLabs', 'ElevenLabs'),
    logoProviderId: 'elevenlabs',
    website: 'https://elevenlabs.io',
    baseUrl: 'https://api.elevenlabs.io/v1',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('xi-api-key'),
    sharedPresetIds: [],
    defaultModel: 'eleven_multilingual_v2',
    models: models(
      'text-to-speech',
      ['eleven_multilingual_v2', 'Eleven Multilingual v2'],
      ['eleven_turbo_v2_5', 'Eleven Turbo v2.5'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.elevenlabs.io/v1/user',
      auth: { type: 'header', fieldId: 'apiKey', headerName: 'xi-api-key' },
    },
  },
  {
    kind: 'audio',
    id: 'together',
    runtimeProviderId: 'together',
    credentialGroupId: 'together',
    names: names('Together AI Audio', 'Together AI 音频'),
    logoProviderId: 'together',
    website: 'https://www.together.ai',
    baseUrl: 'https://api.together.xyz/v1/audio',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'openai/whisper-large-v3-turbo',
    models: mixedModels(
      ['openai/whisper-large-v3-turbo', 'Whisper Large v3 Turbo', 'speech-to-text'],
      ['cartesia/sonic-2', 'Cartesia Sonic 2', 'text-to-speech'],
      ['hexgrad/Kokoro-82M', 'Kokoro 82M', 'text-to-speech'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.together.xyz/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'audio',
    id: 'assemblyai',
    runtimeProviderId: 'assemblyai',
    credentialGroupId: 'assemblyai',
    names: names('AssemblyAI', 'AssemblyAI'),
    logoProviderId: 'assemblyai',
    website: 'https://www.assemblyai.com',
    baseUrl: 'https://api.assemblyai.com/v2/transcript',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'universal-3-pro',
    models: models(
      'speech-to-text',
      ['universal-3-pro', 'Universal 3 Pro'],
      ['universal-2', 'Universal 2'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.assemblyai.com/v2/transcript',
      auth: { type: 'header', fieldId: 'apiKey', headerName: 'authorization' },
    },
  },
  {
    kind: 'audio',
    id: 'cohere',
    runtimeProviderId: 'cohere',
    credentialGroupId: 'cohere',
    names: names('Cohere Transcribe', 'Cohere 语音识别'),
    logoProviderId: 'cohere',
    website: 'https://cohere.com',
    baseUrl: 'https://api.cohere.com/v2/audio/transcriptions',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['cohere'],
    defaultModel: 'cohere-transcribe-03-2026',
    models: models(
      'speech-to-text',
      ['cohere-transcribe-03-2026', 'Cohere Transcribe 2026-03'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.cohere.com/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'audio',
    id: 'nvidia',
    runtimeProviderId: 'nvidia',
    credentialGroupId: 'nvidia',
    names: names('NVIDIA Speech', 'NVIDIA 语音'),
    logoProviderId: 'nvidia',
    website: 'https://build.nvidia.com',
    baseUrl: 'https://integrate.api.nvidia.com/v1/audio',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: ['nvidia'],
    defaultModel: 'nvidia/parakeet-ctc-1.1b-asr',
    models: mixedModels(
      ['nvidia/parakeet-ctc-1.1b-asr', 'Parakeet CTC 1.1B', 'speech-to-text'],
      ['openai/whisper-large-v3', 'Whisper Large v3', 'speech-to-text'],
      ['nvidia/fastpitch', 'FastPitch', 'text-to-speech'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://integrate.api.nvidia.com/v1/models',
      auth: { type: 'bearer', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'audio',
    id: 'huggingface',
    runtimeProviderId: 'huggingface',
    credentialGroupId: 'huggingface',
    names: names('Hugging Face Audio', 'Hugging Face 音频'),
    logoProviderId: 'huggingface',
    website: 'https://huggingface.co/models',
    baseUrl: 'https://api-inference.huggingface.co/models',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('Hugging Face token', 'hf_...'),
    sharedPresetIds: ['huggingface'],
    defaultModel: 'openai/whisper-large-v3-turbo',
    models: mixedModels(
      ['openai/whisper-large-v3-turbo', 'Whisper Large v3 Turbo', 'speech-to-text'],
      ['canopylabs/orpheus-3b-0.1-ft', 'Orpheus 3B', 'text-to-speech'],
      ['hexgrad/Kokoro-82M', 'Kokoro TTS', 'text-to-speech'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'audio',
    id: 'cartesia',
    runtimeProviderId: 'cartesia',
    credentialGroupId: 'cartesia',
    names: names('Cartesia', 'Cartesia'),
    logoProviderId: 'cartesia',
    website: 'https://cartesia.ai',
    baseUrl: 'https://api.cartesia.ai/tts/bytes',
    connectionMode: 'api-key',
    credentialFields: apiKeyField('X-API-Key'),
    sharedPresetIds: [],
    defaultModel: 'sonic-3',
    models: models(
      'text-to-speech',
      ['sonic-3', 'Sonic 3'],
      ['sonic-2', 'Sonic 2'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.cartesia.ai/voices',
      auth: { type: 'header', fieldId: 'apiKey', headerName: 'X-API-Key' },
    },
  },
  {
    kind: 'audio',
    id: 'inworld',
    runtimeProviderId: 'inworld',
    credentialGroupId: 'inworld',
    names: names('Inworld TTS', 'Inworld TTS'),
    logoProviderId: 'inworld',
    website: 'https://inworld.ai',
    baseUrl: 'https://api.inworld.ai/tts/v1/voice',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'inworld-tts-2',
    models: models(
      'text-to-speech',
      ['inworld-tts-2', 'Inworld TTS 2'],
      ['inworld-tts-1.5-mini', 'Inworld TTS 1.5 Mini'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'https://api.inworld.ai',
      auth: { type: 'basic', fieldId: 'apiKey' },
    },
  },
  {
    kind: 'audio',
    id: 'playht',
    runtimeProviderId: 'playht',
    credentialGroupId: 'playht',
    names: names('PlayHT', 'PlayHT'),
    logoProviderId: 'playht',
    website: 'https://play.ht',
    baseUrl: 'https://api.play.ht/api/v2/tts/stream',
    connectionMode: 'credentials',
    credentialFields: playHtCredentials,
    sharedPresetIds: [],
    defaultModel: 'PlayDialog',
    models: models(
      'text-to-speech',
      ['PlayDialog', 'PlayDialog'],
      ['Play3.0-mini', 'Play3.0 Mini'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'audio',
    id: 'pollinations',
    runtimeProviderId: 'pollinations',
    credentialGroupId: 'pollinations',
    names: names('Pollinations Audio', 'Pollinations 音频'),
    logoProviderId: 'pollinations',
    website: 'https://pollinations.ai',
    baseUrl: 'https://gen.pollinations.ai/v1/audio',
    connectionMode: 'api-key',
    credentialFields: apiKeyField(),
    sharedPresetIds: [],
    defaultModel: 'default',
    models: mixedModels(
      ['default', 'Pollinations TTS', 'text-to-speech'],
      ['whisper', 'Pollinations Whisper', 'speech-to-text'],
    ),
    chinaPriority: false,
    source: 'omniroute',
  },
  {
    kind: 'audio',
    id: 'coqui',
    runtimeProviderId: 'coqui',
    credentialGroupId: 'coqui',
    names: names('Coqui TTS (Local)', 'Coqui TTS（本地）'),
    logoProviderId: 'coqui',
    website: 'https://github.com/coqui-ai/TTS',
    baseUrl: 'http://127.0.0.1:5002/api/tts',
    connectionMode: 'local',
    credentialFields: noCredentials,
    sharedPresetIds: [],
    defaultModel: 'tts_models/en/ljspeech/tacotron2-DDC',
    models: models(
      'text-to-speech',
      ['tts_models/en/ljspeech/tacotron2-DDC', 'Tacotron2 DDC'],
    ),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'http://127.0.0.1:5002',
      auth: { type: 'none' },
    },
  },
  {
    kind: 'audio',
    id: 'tortoise',
    runtimeProviderId: 'tortoise',
    credentialGroupId: 'tortoise',
    names: names('Tortoise TTS (Local)', 'Tortoise TTS（本地）'),
    logoProviderId: 'tortoise',
    website: 'https://github.com/neonbjb/tortoise-tts',
    baseUrl: 'http://127.0.0.1:5000/api/tts',
    connectionMode: 'local',
    credentialFields: noCredentials,
    sharedPresetIds: [],
    defaultModel: 'tortoise-v2',
    models: models('text-to-speech', ['tortoise-v2', 'Tortoise v2']),
    chinaPriority: false,
    source: 'omniroute',
    test: {
      url: 'http://127.0.0.1:5000',
      auth: { type: 'none' },
    },
  },
] as const

export const MEDIA_PROVIDERS: readonly MediaProviderDefinition[] = [
  ...IMAGE_PROVIDERS,
  ...VIDEO_PROVIDERS,
  ...AUDIO_PROVIDERS,
] as const

const MEDIA_PROVIDER_BY_KEY = new Map(
  MEDIA_PROVIDERS.map((provider) => [
    getMediaProviderKey(provider.kind, provider.id),
    provider,
  ]),
)

export function getMediaProvidersByKind(
  kind: MediaProviderKind,
): readonly MediaProviderDefinition[] {
  return MEDIA_PROVIDERS.filter((provider) => provider.kind === kind)
}

export function getMediaProvider(
  kind: MediaProviderKind,
  providerId: string,
): MediaProviderDefinition | undefined {
  return MEDIA_PROVIDER_BY_KEY.get(getMediaProviderKey(kind, providerId))
}

export function getMediaProviderKey(
  kind: MediaProviderKind,
  providerId: string,
): string {
  return `${kind}:${providerId}`
}

export function isMediaProviderKind(value: string): value is MediaProviderKind {
  return MEDIA_PROVIDER_KINDS.includes(value as MediaProviderKind)
}

export function getMediaProviderName(
  provider: MediaProviderDefinition,
  locale: string,
): string {
  const normalized = locale === 'zh-CN' ? 'zh' : locale.split('-')[0]
  return provider.names[normalized as MediaProviderLocale] ?? provider.names.en
}
